language: node_js
sudo: required
matrix:
  include:
    - node_js: "8"
      script: "npm test"
    - node_js: "10"
      script: "npm test"
    - node_js: "12"
      script: "npm test"
    - node_js: "14"
      script: "npm run travis"
env:
  - BLUEBIRD_DEBUG=0
